### ISSUE TITLE
VueFire Roadmap 2022-2023

### ISSUE THREAD

**Issue by posva** [vuejs/vuefire#1241]
This is an issue to keep track of the upcoming release of VueFire v3. Note this is a **high level roadmap**, more details are added as I complete them and it helps people to get an overview of how things are going.

- Current Status: Stable
- [Documentation](https://vuefire.vuejs.org/)
- [Branch](https://github.com/vuejs/vuefire/tree/main)

## 1st Milestone

Estimate final delivery (means stable release) time: mid-November

- [x] Cloudstore/Database
  - [x] Upgrade to Firebase v9
  - [x] Migrate test suite to Firebase Emulator
  - [x] Design and implement a composable API for Vue
  - [X] Migrate unit tests
  - [x] Updates to the README
  - [X] Documentation
    - [X] Setup vitepress
    - [X] Add Getting started instructions
    - [X] Automatic API generation
    - [X] Basic documentation for composables
    - [X] Add back the options API docs
    - [X] Update existing docs
    - [x] Using with other libraries (Pinia, Vuex)
    - [X] Add SSR Examples without Nuxt
    - [X] Write a migration Guide from v2
  - [X] Implement an Options API version of the composable API for binding data
  - [X] Rework the existing Options API (improvements based on feedback)
  - [X] Ensure SSR compatibility

The new version of VueFire **is available on the `next` tag as an alpha version**.

## 2nd Milestone

- [X] Plugin rework: allow passing independent services
- [X] Auth module integration
  - [X] Reactive current user
  - [x] Design composables for signin check
  - [x] Investigate possible integrations with router navigation guards
- [X] Storage integration
  - [X] Design composables for uploading tasks
  - [X] Composable for downloading URLs
  - [x] SSR
- [X] AppCheck
  - [x] A plugin that injects the firebase app and allows the user to provide the credentials for recaptcha v3.
  - [x] Add docs
  - [x] Add options to nuxt module
- [x] Nuxt Module/plugin
  - [X] `nuxt-vuefire` package
  - [x] SSR handling out of the box
  - [x] Simple (zero-config or automated) Deployment to Firebase Hosting
    - [x] Spark plan (no functions)
    - [x] Blaze plan (with functions)
  - [x] Document good practices around prerending
  - [x] Document the different possibilities when deploying (SSR, SSG, SPA, mixed)
  - [ ] Explore other providers (Netlify, Vercel, etc)
  - [ ] TBD: other features worth integrating
  
## Backlog

- [ ] Add API to automatically handle the SSR part for non reactive API like `await list()` for storage

# Other issues

These is a list of feature requests I want to revisit:

- https://github.com/vuejs/vuefire/issues/955
- https://github.com/vuejs/vuefire/issues/608
- https://github.com/vuejs/vuefire/issues/685 ~~should this be possible? Is `withConverter()` enough?~~
- https://github.com/vuejs/vuefire/issues/245

**Comment by hoanghadu** [comment]
Thanks @posva for the hard work. Wish that the Nuxt Module would be finished soon.

**Comment by posva** [comment]
Thanks! It actually has a lot of features already, you should give it a try 🙂

**Comment by posva** [comment]
I realize I never closed this but it was completed a long while ago 😄

**Comment by crunchwrap89** [comment]
Hi,
Is there any plans for adding analytics to the project?
I see there is some experimental and unfinished code around this in the package.
